### PR TITLE
Allow extending datasets not yet staged

### PR DESCRIPTION
**Pull request by nafiz1001**

### CODE REVIEW

**Comment by samouzegar10** [comment]
overall looks good, the only comment i would say is that the file is somewhat large and contains many different components and actions that could be encapsulated together

**Review by samouzegar10 — COMMENTED** [review]
the only comment i have is left on the general comment section of the pr

**Comment by nafiz1001** [comment]
> overall looks good, the only comment i would say is that the file is somewhat large and contains many different components and actions that could be encapsulated together

I'm currently working on that feedback. So the PR is not ready yet.

**Review by samouzegar10 — COMMENTED** [review]
i rechecked the pr and it still looks good. now you have added an additional level of modularity, its a good thing.

If you really want to kick this ball of the park, a homerun one could say, you could have datasetCard component encapsulated in its own directory with the datasetCardButton folder nested within since the datasetCardButton is very specific to the datasetCard.

 It would be an great change but not a necessary one.

**Pull request merged**
